---
inherit_from: .rubocop_todo.yml

inherit_gem:
  voxpupuli-rubocop: rubocop.yml

Style:
  Enabled: false

Layout:
  Enabled: false

# To match the gem name
Naming/FileName:
  Exclude:
    - 'lib/rspec-puppet-facts.rb'
