---
name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

permissions:
  contents: read # minimal permissions that we have to grant

jobs:
  rubocop_and_matrix:
    runs-on: ubuntu-24.04
    outputs:
      ruby: ${{ steps.ruby.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop
      - id: ruby
        uses: voxpupuli/ruby-version@v1

  test:
    needs: rubocop_and_matrix
    name: "Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJSON(needs.rubocop_and_matrix.outputs.ruby) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rake spec
      - name: Test gem build
        run: gem build --strict --verbose *.gemspec

  tests:
    needs:
      - rubocop_and_matrix
      - test
    runs-on: ubuntu-24.04
    name: Test suite
    steps:
      - run: echo Test suite completed
