name: Test

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_WITHOUT: release
      - name: Run unit tests
        run: bundle exec rake spec
      - name: Test against Puppet component versions
        run: bundle exec rake puppet_versions:test
      - name: Test gem build
        run: bundle exec rake build
